### ISSUE TITLE
Obra

### ISSUE THREAD

**Issue by Yair95** [IsaackHazaell/ABCaptura#34]
Create:
-Que el label de honorary diga "Porcentaje de honorarios"
-Que el label de date diga "Fecha de arranque"
-Agregar el formulario de client (Para esto primero se debe terminar el modulo client (issues 33))

Delete:
Que elimine una obra (Actualmente no funciona)

**Comment by IsaackHazaell** [comment]
No puedo mandar el swet alert después de eliminar, si elimina, pero tengo que recargar automáticamente.
