### ISSUE TITLE
Fund

### ISSUE THREAD

**Issue by Yair95** [IsaackHazaell/ABCaptura#36]
Create:
-quitar el input "restante", pues si recién creamos un fondo sabemos que el restante es igual al total, por lo que al guardarlo (store) simplemente se iguala el campo total con restante

-Delete: Que se pueda borrar un fondo

Index: Problemas con las fechas, al mostrarlas en el datatable parece que solo agarra la del primer registro

-Siempre que se muestre una fecha, hacerlo en este formato: dd-ENE-aaaa (En los meses utilizar las tres primeras letras del mes: ENE, FEB, MAR, ABR...) Hacer esto en el show y en el index

**Comment by IsaackHazaell** [comment]
Create:
Solucionado.
- Ya se elimino el campo restante 
- Ya se puede borrar un fondo 
- No detecte problemas con las fechas
Problemas.
- No tengo ni idea como hacer este cambio
- No entra el mostrar fondo
